### ISSUE TITLE
Error: Header must contain atleast one of these two fields - DeveloperName, Label.

### ISSUE THREAD

**Issue by millerterry** [forcedotcom/CustomMetadataLoader#20]
I get the following error even though the first row of my csv file has a column called Label.

Error:
Header must contain atleast one of these two fields - DeveloperName, Label.

**Comment by Bard09** [comment]
I just experienced this error as well.  I did 2 things that seemed to resolve it:

1. Moved both of those 2 columns to the first 2 columns in the CSV
2. Changed the case from All Caps to match the formatting in the error, eg. DeveloperName instead of DEVELOPERNAME

Not sure which is the actual fix, but I assume the devs can look into it :)

**Comment by sricharananand** [comment]
please use DeveloperName and Label as first two columns in csv. Also make sure cmd values in DeveloperName doesn't contain any spaces, underscore etc.

**Comment by sc5148** [comment]
Use **Windows Comma Separated** or **Mac Comma Separated** format while saving the excel, instead of just .csv. It should work.

**Comment by bishwambharsen** [comment]
Even I am facing the same issue. Have also tried the Windows Comma Separated file which gave me a BLOB related issue.

**Comment by bishwambharsen** [comment]
Fixed it by using the CSV formatted under Specialty formats instead of the one under Common formats. This is for MacOS. PFA the screenshot for reference.
<img width="423" alt="Screenshot 2019-05-08 at 12 17 30 AM" src="https://user-images.githubusercontent.com/42896415/57315800-ec613400-7126-11e9-8cc2-b94d39e5700d.png">
