### ISSUE TITLE
Attempt to de-reference a null object

### ISSUE THREAD

**Issue by bsankardas04** [forcedotcom/CustomMetadataLoader#24]
Attempt to de-reference a null object
Error is in expression '{!upsertCustomMetadata}' in component <apex:commandButton> in page custommetadatarecorduploader: Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1

**Comment by Yogesh-Sinhal** [comment]
1) This issue is observed due to change in field delimiter , The delimiter in file should be ";" ( Semicolon ) and not ',' (Comma) 

2) Even if you use ";" (semicolon) delimiter and your data field contains "," ( Comma ) you might get errors , This issue can be fixed by  changing line 45 of CSVFileUtil.cls 
from  List<String> fields = line.split(',');   to  List<String> fields = line.split('#');  ( Or any other character which is not part of your data of delimiter.

3) CSVFileUtil.cls  needs to be re-written as piece code of have lost relevance with delimiter being ";" (semicolon) - Optional

**Comment by sricharananand** [comment]
Issue should be resolved now via commit on Aug 9, 2017 - closing this issue.
